"""Appointment origin channels (web, WhatsApp, future providers)."""

from __future__ import annotations

APPOINTMENT_SOURCE_WEB = "WEB"
APPOINTMENT_SOURCE_WHATSAPP = "WHATSAPP"
APPOINTMENT_SOURCE_ADMIN = "ADMIN"

APPOINTMENT_SOURCES = (
    APPOINTMENT_SOURCE_WEB,
    APPOINTMENT_SOURCE_WHATSAPP,
    APPOINTMENT_SOURCE_ADMIN,
)

APPOINTMENT_SOURCE_LABELS = {
    APPOINTMENT_SOURCE_WEB: "Site",
    APPOINTMENT_SOURCE_WHATSAPP: "WhatsApp",
    APPOINTMENT_SOURCE_ADMIN: "Admin",
}
